name: test2
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:


    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Generate Report
      run: |
        pip install coverage
        coverage run -m unittest
        
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v3
      with:
          name: unittest
          path: math-homework.txt
